//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corps
    {
        public Corps()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int Corps_ID { get; set; }
        public string CorpsName { get; set; }
        public string Adress { get; set; }
    
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
