//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEquipment
    {
        public int EmployeeEquipment_ID { get; set; }
        public int EquipmentLeasing_ID { get; set; }
        public int Equipment_ID { get; set; }
        public int Quantity { get; set; }
    
        public virtual EquipmentLeasing EquipmentLeasing { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
