//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeRooms = new HashSet<EmployeeRoom>();
            this.EquipmentLeasings = new HashSet<EquipmentLeasing>();
            this.EquipmentLeasings1 = new HashSet<EquipmentLeasing>();
            this.Users = new HashSet<User>();
        }
    
        public int Employee_ID { get; set; }
        public int Post_ID { get; set; }
        public Nullable<int> Organization_ID { get; set; }
        public string FName { get; set; }
        public string EmpName { get; set; }
        public string LName { get; set; }
        public string Phone { get; set; }
        public bool IsArchive { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<EmployeeRoom> EmployeeRooms { get; set; }
        public virtual Post Post { get; set; }
        public virtual ICollection<EquipmentLeasing> EquipmentLeasings { get; set; }
        public virtual ICollection<EquipmentLeasing> EquipmentLeasings1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
