//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.EmployeeEquipments = new HashSet<EmployeeEquipment>();
            this.RoomEquipments = new HashSet<RoomEquipment>();
            this.WriteOffEquipments = new HashSet<WriteOffEquipment>();
        }
    
        public int Equipment_ID { get; set; }
        public Nullable<int> Manufacturer_ID { get; set; }
        public Nullable<int> EquipmentType_ID { get; set; }
        public int BalanceType_ID { get; set; }
        public string Serial { get; set; }
        public string EquipmentName { get; set; }
        public int Quantity { get; set; }
        public string InventoryNumber { get; set; }
        public string Notice { get; set; }
        public string Model { get; set; }
    
        public virtual BalanceType BalanceType { get; set; }
        public virtual ICollection<EmployeeEquipment> EmployeeEquipments { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<RoomEquipment> RoomEquipments { get; set; }
        public virtual ICollection<WriteOffEquipment> WriteOffEquipments { get; set; }
    }
}
