//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentType
    {
        public EquipmentType()
        {
            this.Equipments = new HashSet<Equipment>();
        }
    
        public int EquipmentType_ID { get; set; }
        public string EquipmentTypeName { get; set; }
    
        public virtual ICollection<Equipment> Equipments { get; set; }
    }
}
