//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentDB.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EquipmentDBEntities : DbContext
    {
        public EquipmentDBEntities()
            : base("name=EquipmentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BalanceType> BalanceTypes { get; set; }
        public DbSet<Corps> Corps { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeeEquipment> EmployeeEquipments { get; set; }
        public DbSet<EmployeeRoom> EmployeeRooms { get; set; }
        public DbSet<Equipment> Equipments { get; set; }
        public DbSet<EquipmentLeasing> EquipmentLeasings { get; set; }
        public DbSet<EquipmentType> EquipmentTypes { get; set; }
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<RoomEquipment> RoomEquipments { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WriteOffEquipment> WriteOffEquipments { get; set; }
    }
}
