//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.EmployeeRooms = new HashSet<EmployeeRoom>();
            this.RoomEquipments = new HashSet<RoomEquipment>();
        }
    
        public int Room_ID { get; set; }
        public int Corps_ID { get; set; }
        public string RoomName { get; set; }
    
        public virtual Corps Corps { get; set; }
        public virtual ICollection<EmployeeRoom> EmployeeRooms { get; set; }
        public virtual ICollection<RoomEquipment> RoomEquipments { get; set; }
    }
}
